main:
  - identifier: about
    name: About
    url: /about/
    weight: 1
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 2
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 3
  - identifier: search
    name: Search
    url: /search/
    weight: 4